// const icons = [
//     { icon: "fas fa-grin-hearts", name: "hearts" },
//     { icon: "far fa-grin-hearts", name: "hearts" },
//     { icon: "fas fa-grin-squint", name: "squint" },
//     { icon: "far fa-grin-squint", name: "squint" },
//     { icon: "fas fa-grin-squint-tears", name: "tears" },
//     { icon: "far fa-grin-squint-tears", name: "tears" },
//     { icon: "fas fa-grin-stars", name: "stars" },
//     { icon: "far fa-grin-stars", name: "stars" },
//     { icon: "fas fa-grin-tears", name: "tears" },
//     { icon: "far fa-grin-tears", name: "tears" },
//     { icon: "fas fa-grin-tongue", name: "tongue" },
//     { icon: "far fa-grin-tongue", name: "tongue" },
//     { icon: "fas fa-grin-tongue-squint", name: "tongue" },
//     { icon: "far fa-grin-tongue-squint", name: "tongue" },
//     { icon: "fas fa-grin-tongue-wink", name: "tongue" },
//     { icon: "far fa-grin-tongue-wink", name: "tongue" },
//     { icon: "fas fa-kiss", name: "kiss" },
//     { icon: "far fa-kiss", name: "kiss" },
//     { icon: "fas fa-kiss-beam", name: "kiss" },
//     { icon: "far fa-kiss-beam", name: "kiss" },
//     { icon: "fas fa-kiss-wink-heart", name: "kiss" },
//     { icon: "far fa-kiss-wink-heart", name: "kiss" },
//     { icon: "fas fa-laugh-squint", name: "laugh" },
//     { icon: "far fa-laugh-beam", name: "laugh" },
//     { icon: "far fa-laugh", name: "laugh" },
//     { icon: "fas fa-smile", name: "smile" },
//     { icon: "far fa-smile", name: "smile" },
//     { icon: "fas fa-smile-beam", name: "smile" },
//     { icon: "far fa-smile-beam", name: "smile" },
//     { icon: "fas fa-smile-wink", name: "smile" },
//     { icon: "far fa-smile-wink", name: "smile" },
//     { icon: "fas fa-sad-cry", name: "cry" },
//     { icon: "far fa-sad-cry", name: "cry" },
//     { icon: "fas fa-sad-tear", name: "cry" },
//     { icon: "far fa-sad-tear", name: "cry" },
//     { icon: "fas fa-angry", name: "angry" },
//     { icon: "far fa-angry", name: "angry" },
//     { icon: "fas fa-dizzy", name: "dizzy" },
//     { icon: "far fa-dizzy", name: "dizzy" },
//     { icon: "fas fa-flushed", name: "flushed" },
//     { icon: "far fa-flushed", name: "flushed" },
//     { icon: "fas fa-frown", name: "frown" },
//     { icon: "far fa-frown", name: "frown" },
//     { icon: "fas fa-grin", name: "grin" },
//     { icon: "far fa-grin", name: "grin" },
//     { icon: "fas fa-grin-beam", name: "grin" },
//     { icon: "far fa-grin-beam", name: "grin" },
//     { icon: "fas fa-grin-beam-sweat", name: "grin" },
//     { icon: "far fa-grin-beam-sweat", name: "grin" },
//     { icon: "fas fa-grin-squint", name: "grin" },
//     { icon: "far fa-grin-squint", name: "grin" },
//     { icon: "fas fa-grin-sweat", name: "grin" },
//     { icon: "far fa-grin-sweat", name: "grin" },
//     { icon: "fas fa-grin-tears", name: "grin" },
//     { icon: "far fa-grin-tears", name: "grin" },
//     { icon: "fas fa-grin-tongue", name: "grin" },
//     { icon: "far fa-grin-tongue", name: "grin" },
//     { icon: "fas fa-grin-tongue-squint", name: "grin" },
//     { icon: "far fa-grin-tongue-squint", name: "grin" },
//     { icon: "fas fa-grin-tongue-wink", name: "grin" },
//     { icon: "far fa-grin-tongue-wink", name: "grin" },
//     { icon: "fas fa-grin-stars", name: "grin" },
//     { icon: "far fa-grin-stars", name: "grin" },
//     { icon: "fas fa-grin-alt", name: "grin" },
//     { icon: "far fa-grin-alt", name: "grin" },
//     { icon: "fas fa-grimace", name: "grimace" },
//     { icon: "far fa-grimace", name: "grimace" },
//     { icon: "fas fa-heart-eyes", name: "heart-eyes" },
//     { icon: "far fa-heart-eyes", name: "heart-eyes" },
//     { icon: "fas fa-kiss", name: "kiss" },
//     { icon: "far fa-kiss", name: "kiss" },
//     { icon: "fas fa-kiss-beam", name: "kiss" },
//     { icon: "far fa-kiss-beam", name: "kiss" },
//     { icon: "fas fa-kiss-wink-heart", name: "kiss" },
//     { icon: "far fa-kiss-wink-heart", name: "kiss" },
//     { icon: "fas fa-laugh", name: "laugh" },
//     { icon: "far fa-laugh", name: "laugh" },
//     { icon: "fas fa-laugh-beam", name: "laugh" },
//     { icon: "far fa-laugh-beam", name: "laugh" },
//     { icon: "fas fa-laugh-squint", name: "laugh" },
//     { icon: "far fa-laugh-squint", name: "laugh" },
//     { icon: "fas fa-laugh-wink", name: "laugh" },
//     { icon: "far fa-laugh-wink", name: "laugh" },
//     { icon: "fas fa-meh", name: "meh" },
//     { icon: "far fa-meh", name: "meh" },
//     { icon: "fas fa-meh-blank", name: "meh" },
//     { icon: "far fa-meh-blank", name: "meh" },
//     { icon: "fas fa-meh-rolling-eyes", name: "meh" },
//     { icon: "far fa-meh-rolling-eyes", name: "meh" },
//     { icon: "fas fa-sad-cry", name: "sad" },
//     { icon: "far fa-sad-cry", name: "sad" },
//     { icon: "fas fa-sad-tear", name: "sad" },
//     { icon: "far fa-sad-tear", name: "sad" },
//     { icon: "fas fa-surprise", name: "surprise" },
//     { icon: "far fa-surprise", name: "surprise" },
//     { icon: "fas fa-tired", name: "tired" },
//     { icon: "far fa-tired", name: "tired" },
//     { icon: "fas fa-grimace", name: "grimace" },
//     { icon: "far fa-grimace", name: "grimace" },
//     { icon: "fas fa-tired", name: "tired" },
//     { icon: "far fa-tired", name: "tired" },
//     { icon: "fas fa-angry", name: "angry" },
//     { icon: "far fa-angry", name: "angry" },
//     { icon: "fas fa-flushed", name: "flushed" },
//     { icon: "far fa-flushed", name: "flushed" },
//     { icon: "fas fa-dizzy", name: "dizzy" },
//     { icon: "far fa-dizzy", name: "dizzy" },
//     { icon: "fas fa-frown", name: "frown" },
//     { icon: "far fa-frown", name: "frown" },
//     { icon: "fas fa-grin", name: "grin" },
//     { icon: "far fa-grin", name: "grin" },
//     { icon: "fas fa-grin-alt", name: "grin" },
//     { icon: "far fa-grin-alt", name: "grin" },
//     { icon: "fas fa-grin-beam", name: "grin" },
//     { icon: "far fa-grin-beam", name: "grin" },
//     { icon: "fas fa-grin-beam-sweat", name: "grin" },
//     { icon: "far fa-grin-beam-sweat", name: "grin" },
//     { icon: "fas fa-grin-hearts", name: "grin" },
//     { icon: "far fa-grin-hearts", name: "grin" },
//     { icon: "fas fa-grin-squint", name: "grin" },
//     { icon: "far fa-grin-squint", name: "grin" },
//     { icon: "fas fa-grin-sweat", name: "grin" },
//     { icon: "far fa-grin-sweat", name: "grin" },
//     { icon: "fas fa-grin-tears", name: "grin" },
//     { icon: "far fa-grin-tears", name: "grin" },
//     { icon: "fas fa-grin-tongue", name: "grin" },
//     { icon: "far fa-grin-tongue", name: "grin" },
//     { icon: "fas fa-grin-tongue-squint", name: "grin" },
//     { icon: "far fa-grin-tongue-squint", name: "grin" },
//     { icon: "fas fa-grin-tongue-wink", name: "grin" },
//     { icon: "far fa-grin-tongue-wink", name: "grin" },
//     { icon: "fas fa-grin-stars", name: "grin" },
//     { icon: "far fa-grin-stars", name: "grin" },
// ];

// export default icons;
// hard coded icons data
import icons from "./data";
let say = document.getElementById("searchInput").addEventListener("input", function () {
    serchIcons(this.value);
});
console.log(say);
// function for load data   
function loadIcons(searchValue = "") {
    var el = document.querySelector(".emoji-container");
    var innerData = "";
    icons.forEach(function (item) {
        if (item.name.includes(searchValue)) {
            innerData += `
        <div>
        <i class="${item.icon}"></i>
        <p>${item.icon}</p>
        </div>`;
        }

    });

    el.innerHTML = innerData;
}
// function searchIcon(val) {
//     loadIcons(val)
// }

// loadIcons()